#!/usr/bin/env python
#
# Copyright 2010 Mark Fiers
# This tool is part of Hagfish & distributed under the GPL
# please see COPYING for details
#

import os
import sys
import math

import numpy as np
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import matplotlib as mpl
#import matplotlib.transforms
#import matplotlib.rc as rc
import pylab as pl

import subprocess

from hagfishUtils import *

data = np.load(os.path.join('bins', sys.argv[1] + '.bins.npz'))
bins = data['bins']

mpl.rcParams['axes.labelsize'] = 'x-small'
mpl.rcParams['axes.titlesize'] = 'small'
mpl.rcParams['xtick.labelsize'] = 'xx-small'
mpl.rcParams['ytick.labelsize'] = 'xx-small'


fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111)
ax.imshow(bins)

outfile = sys.argv[1] + '.bins.png'
plt.savefig('%s' % (outfile), dpi=100)

