#!/usr/bin/env python

import os
import sys
import pickle

import numpy as np

import logging
import optparse

## Arguments: General options 
parser = optparse.OptionParser()
parser.set_defaults(binSize=500, source='hagfish')
parser.add_option('-v', dest='verbose', action="count", 
                  help='Show debug information')
parser.add_option('-s', dest='source', 
                  help='Source field for the GFF output')
parser.add_option('-b', dest='binSize',  type='int',
                  help='binSize')

options, args = parser.parse_args()

l = logging.getLogger('hagfish')
handler = logging.StreamHandler()
logmark = chr(27) + '[0;37;44mHAGFISH' + \
          chr(27) + '[0m ' 

formatter = logging.Formatter(
    logmark + '%(levelname)-6s %(message)s')

handler.setFormatter(formatter)
l.addHandler(handler)

if options.verbose >= 2:
    l.setLevel(logging.DEBUG)
elif options.verbose == 1:
    l.setLevel(logging.INFO)
else:
    l.setLevel(logging.WARNING)


def generate_histogram(F,
                       seqId,
                       group,
                       data, 
                       bin,
                       source,
                       seqLen):
    
    if bin == 1:
        for i in range(len(data)):
            v = data[i]
            F.write("\t".join([
                        seqId,
                        source,
                        'bin_%s_%s' % (group, bin),
                        str(i+1),
                        str(i+2),
                        '%d' % v,
                        '+',
                        '.',
                        'bin %s:%s' % (seqId, source)
                        ]) + "\n")
    else:
        for r in range(0, len(data)+bin-1,bin):
            bestart = r+1
            if bestart > seqLen:
                continue
            beend = min(seqLen+1, r+bin)
            va = '%.1f' % np.average(data[r:r+bin-1])
            if va == 'nan': va = '0'
        

            F.write("\t".join([
                seqId,
                source,
                'bin_%s_%s' % (group, bin),
                str(bestart),
                str(beend),
                va,
                '+',
                '.',
                'bin %s_%s' % (source, seqId)
                ]) + "\n")
            
if __name__ == '__main__':
    
    #read all seqId file
    seqInfo = {}
    for f in os.listdir('seqInfo'):
        if '.seqinfo' in f:
            seqInfoFile = os.path.join('seqInfo', f)
            l.info("reading %s to get seqinfo" % seqInfoFile)
            with open(seqInfoFile) as F:
                _tsi = pickle.load(F)
                seqInfo.update(_tsi)
    if not seqInfo:
        l.critical("cannot find a seqInfo file")
        sys.exit(-1)
        
    l.info("Found %d sequences" % len(seqInfo))

    binSize = options.binSize
    if len(args) > 0:
        seqIds = args
    else:
        seqIds = seqInfo.keys()

    if not os.path.exists('gff'):
        os.mkdir('gff')

    for seqId in seqIds:

        FG = open(os.path.join('gff', '%s.ok.%d.gff' % (seqId, binSize)), 'w')
        FS = open(os.path.join('gff', '%s.short.%d.gff' % (seqId, binSize)), 'w')
        FL = open(os.path.join('gff', '%s.long.%d.gff' % (seqId, binSize)), 'w')

        FG.write("##gff-version 3\n")
        FS.write("##gff-version 3\n")
        FL.write("##gff-version 3\n")
        seqLen = seqInfo[seqId]['length']
        
        FG.write("##sequence-region %s 1 %d\n" % (seqId, seqLen))
        FS.write("##sequence-region %s 1 %d\n" % (seqId, seqLen))
        FL.write("##sequence-region %s 1 %d\n" % (seqId, seqLen))

        coverageFile = os.path.join('combined', '%s.combined.coverage.npz' % seqId)
        if not os.path.exists(coverageFile):
            continue
        l.info('processing %s' % coverageFile)
        data = np.load(coverageFile)
        r_ok = data['r_ok']
        r_low = data['r_low']
        r_high = data['r_high']

        if not np.any(r_ok):
            l.error("Error reading data for %s" % seqId)
            l.error(" .. in %s" % os.getcwd())
            continue
    
        seqLen = len(r_ok)
        l.info("sequence length of %s is %d" % (seqId, seqLen))
        generate_histogram(FG, seqId, 'ok',    r_ok,   binSize, options.source, seqLen)
        generate_histogram(FS, seqId, 'short', r_low,  binSize, options.source, seqLen)
        generate_histogram(FL, seqId, 'long',  r_high, binSize, options.source, seqLen)

        FG.close()
        FS.close()
        FL.close()
        
        l.info("Finished processing %s" % seqId)

